version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-employee
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/employee
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password

volumes:
  postgres-data:
