lversion: '3.8'

services:
  app:
    image: myapp:latest
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/employee
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_MAIL_USERNAME=${secrets.MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${secrets.MAIL_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgresdb
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=employee
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
